---
name: Wisdom for Wanderers
locales: [en]
seo_title: Travel Tips for the Adventurous
meta_keywords: travel backpacking budget adventure
meta_description: Learn about cool places to see abroad, interesting things to eat,
  and little travel tips you won't believe you lived without.
timezone: Mexico City
